### ISSUE TITLE
Imagens do projeto no README

### ISSUE THREAD

**Issue by 11808s8** [vitorueno/BombAnimal#1]
Acho que seria interessante ter algumas telas do game (ou todas possíveis haha!) pra demonstrar suas funcionalidades, logo no README. Isso já até desperta a curiosidade em quem está olhando o repo também.<br> Exemplos de lugares em que já ví algo assim: [exemplo 1](https://github.com/kitao/pyxel), [exemplo 2](https://github.com/kittykatattack/ga)

**Comment by vitorueno** [comment]
massa! 

vou fazer isso

**Comment by vitorueno** [comment]
coloquei algumas fotos, não sei o que você achou

**Comment by 11808s8** [comment]
Achei que ficou bem interessante! Ajuda a chamar a atenção já na leitura do repo. Massa!
